#!/usr/bin/env python3
"""Scaffold every route from the Musicosy Ad Center tree."""
import os

BASE = "/home/z/my-project/src/app/ads"

routes = [
    "campaigns",
    "campaigns/create",
    "campaigns/create/objective",
    "campaigns/create/objective-sub",
    "campaigns/create/delivery-goal",
    "campaigns/create/name",
    "campaigns/create/special-category",
    "campaigns/create/split-test",
    "campaigns/create/cbo",
    "campaigns/create/budget-strategy",
    "campaigns/create/budget-config",
    "campaigns/create/budget-commitment",
    "campaigns/create/budget-tiers",
    "campaigns/create/budget-tier-matrix",
    "campaigns/create/delivery-likelihood",
    "campaigns/create/estimates",
    "campaigns/create/rebate",
    "campaigns/create/method",
    "campaigns/create/audiences",
    "campaigns/create/bidding",
    "campaigns/create/brand-safety",
   "campaigns/create/placements",
    "campaigns/create/targeting",
    "campaigns/create/delivery-type",
    "campaigns/create/frequency-capping",
    "campaigns/create/ad-group-budget",
    "campaigns/[id]",
    "campaigns/[id]/edit",
    "campaigns/[id]/delete",
    "campaigns/[id]/duplicate",
    "campaigns/[id]/pause",
    "campaigns/[id]/resume",
    "campaigns/all",
    "campaigns/search",
    "campaigns/action-request",
    "campaigns/actions",
    "campaigns/groups",
    "campaigns/groups/create",
    "campaigns/groups/[id]",
    "campaigns/groups/[id]/edit",
    "campaigns/groups/[id]/budget",
    "campaigns/groups/[id]/delivery",
    "campaigns/groups/[id]/frequency",
    "campaigns/groups/[id]/cross-format",
    "audiences",
    "audiences/create",
    "audiences/[id]",
    "audiences/[id]/edit",
    "audiences/demographics",
    "audiences/age",
    "audiences/gender",
    "audiences/language",
    "audiences/location",
    "audiences/music-behavior",
    "audiences/artist-affinity",
    "audiences/custom",
    "audiences/exclude",
    "audiences/controls",
    "audiences/size",
    "audiences/insights",
    "creatives",
    "creatives/audio",
    "creatives/audio/upload",
    "creatives/audio/preview",
    "creatives/companion",
    "creatives/companion/upload",
    "creatives/companion/fallback",
    "creatives/companion/persistence",
    "creatives/cta",
    "creatives/destination",
    "creatives/logo",
    "creatives/overlay",
    "creatives/preview",
    "creatives/library",
    "creatives/library/[id]",
    "creatives/library/bulk",
    "creatives/library/search",
    "creatives/library/tags",
    "creatives/library/versions",
    "creatives/ai",
    "creatives/ai/script",
    "creatives/ai/voiceover",
    "creatives/ai/music",
    "creatives/ai/templates",
    "creatives/ai/video",
    "analytics",
    "analytics/overview",
    "analytics/campaigns",
    "analytics/ad-groups",
    "analytics/ads",
    "analytics/audience",
    "analytics/audience/age",
    "analytics/audience/gender",
    "analytics/audience/genre",
    "analytics/audio-engagement",
    "analytics/video-engagement",
    "analytics/video-insights",
    "analytics/clicks",
    "analytics/conversions",
    "analytics/impressions",
    "analytics/reach",
    "analytics/delivery",
    "analytics/cpa",
    "analytics/cpc",
    "analytics/cpm",
    "analytics/roas",
    "analytics/revenue",
    "analytics/streams",
    "analytics/svi",
    "analytics/comments",
    "analytics/attribution",
    "analytics/creative-inspiration",
    "analytics/experiments",
    "analytics/reports",
    "analytics/reports/create",
    "analytics/reports/export",
    "analytics/reports/schedule",
    "account",
    "account/profile",
    "account/brand-safety",
    "account/documents",
    "account/health",
    "account/notifications",
    "account/notifications/settings",
    "account/notifications/tabs",
    "account/targeting",
    "account/verification",
    "account/verification/start",
    "account/verification/status",
    "account/team",
    "account/team/invite",
    "account/team/permissions",
    "account/team/[id]",
    "account/team/[id]/edit",
    "account/team/[id]/remove",
    "account/tiers",
    "account/tiers/status",
    "account/tiers/upgrade",
    "billing",
    "billing/transactions",
    "billing/invoices",
    "billing/invoices/[id]",
    "billing/payment-methods",
    "billing/payment-methods/add",
    "billing/credits",
    "billing/rebates",
    "billing/settings",
    "billing/tax",
    "leads",
    "leads/[id]",
    "leads/instant-forms",
    "leads/direct-messages",
    "leads/website-forms",
    "leads/message-assistant",
    "leads/crm",
    "leads/export",
    "leads/filter",
    "catalog",
    "catalog/shopify",
    "catalog/feed",
    "catalog/manual",
    "catalog/storefront",
    "catalog/products",
    "catalog/products/[id]",
    "catalog/products/[id]/edit",
    "catalog/formats",
    "catalog/formats/carousel",
    "catalog/formats/shoppable",
    "catalog/formats/product-showcase",
    "inventory",
    "inventory/automatic",
    "inventory/catalog",
    "inventory/feed-audio",
    "inventory/feed-video",
    "inventory/search",
    "inventory/top-feed",
    "inventory/performance",
    "exchange",
    "exchange/openrtb",
    "exchange/open-auction",
    "exchange/pmp",
    "exchange/programmatic-guaranteed",
    "exchange/partners",
    "exchange/daast",
    "exchange/vaast",
    "exchange/reconciliation",
    "events",
    "events/customization",
    "events/partners",
    "events/data-sources",
    "events/data-sources/app",
    "events/data-sources/crm",
    "events/data-sources/shop",
    "events/data-sources/website",
    "ai/skills",
    "ai/skills/[id]",
    "ai/skills/browse",
    "ai/skills/mcp",
    "ai/skills/search",
    "agency",
    "agency/billing",
    "agency/clients",
    "agency/clients/[id]",
    "agency/clients/add",
    "agency/cross-client",
    "agency/team",
    "dashboard",
    "dashboard/actions",
    "dashboard/all-campaigns",
    "dashboard/breakdown",
    "dashboard/clickers",
    "dashboard/columns",
    "dashboard/count",
    "dashboard/ctr",
    "dashboard/date-range",
    "dashboard/report",
    "dashboard/search",
    "dashboard/toggle",
    "settings",
    "settings/api",
    "settings/brand-safety",
    "settings/notifications",
    "settings/targeting-defaults",
]

def route_title(path):
    last = path.split("/")[-1]
    last = last.replace("[id]", "Detail")
    return last.replace("-", " ").title()

def safe_component_name(title):
    return title.replace(" ", "").replace("/", "")

count = 0
for route in routes:
    dir_path = os.path.join(BASE, route)
    os.makedirs(dir_path, exist_ok=True)
    page_path = os.path.join(dir_path, "page.tsx")
    if os.path.exists(page_path):
        continue
    title = route_title(route)
    comp = safe_component_name(title)
    content = f'''export default function {comp}Page() {{
  return (
    <div>
      <h1 className="font-display text-2xl font-bold tracking-tight text-neutral-900">{title}</h1>
      <p className="mt-2 text-sm text-neutral-500">This page is under construction.</p>
    </div>
  );
}}
'''
    with open(page_path, "w") as f:
        f.write(content)
    count += 1

print(f"Created {count} new page stubs out of {len(routes)} total routes")
